-- CreateEnum
CREATE TYPE "Role" AS ENUM ('WAREHOUSE_WORKER', 'WAREHOUSE_MANAGER', 'GLOBAL_MANAGER');

-- AlterTable
ALTER TABLE "user" ADD COLUMN     "role" "Role" NOT NULL DEFAULT 'WAREHOUSE_WORKER';
